name: Autograding Tests
'on':
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch tests
      uses: actions/checkout@v4
      with:
        repository: ICM0002/palindrome-tests
        path: temp_tests

    - name: Move test file to root
      run: |
        mv temp_tests/test_palindrome.py test_palindrome.py
        rm -rf temp_tests

    - name: Palindrom Tests
      id: palindrome-tests
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: ''

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PALINDROM-TESTS_RESULTS: "${{steps.palindrome-tests.outputs.result}}"
      with:
        runners: palindrome-tests
